// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm_EmKd4znaD7kWGp7lXp_uKj7hMEbp5c',
    appId: '1:922577193586:web:3874ceb74223b5b41710eb',
    messagingSenderId: '922577193586',
    projectId: 'needlinc-3cea4',
    authDomain: 'needlinc-3cea4.firebaseapp.com',
    storageBucket: 'needlinc-3cea4.appspot.com',
    measurementId: 'G-PF46N62SRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFRyiK9SBX1rii0264tbDcNyGVRNeiw9I',
    appId: '1:922577193586:android:ea595f3ae817096c1710eb',
    messagingSenderId: '922577193586',
    projectId: 'needlinc-3cea4',
    storageBucket: 'needlinc-3cea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYb-qv9ZfC_wRu23nQXC0kvTDCdwBj5o',
    appId: '1:922577193586:ios:55144bd0d6a66c641710eb',
    messagingSenderId: '922577193586',
    projectId: 'needlinc-3cea4',
    storageBucket: 'needlinc-3cea4.appspot.com',
    iosBundleId: 'com.needlinc.needlinc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWYb-qv9ZfC_wRu23nQXC0kvTDCdwBj5o',
    appId: '1:922577193586:ios:59082592ad7fda5d1710eb',
    messagingSenderId: '922577193586',
    projectId: 'needlinc-3cea4',
    storageBucket: 'needlinc-3cea4.appspot.com',
    iosBundleId: 'com.needlinc.needlinc.RunnerTests',
  );
}
